packaging_format = 2

id = "rallly"
name = "Rallly"
description.en = "Tool for creating scheduling polls"
description.fr = "Outil de création de sondages de planification"

version = "4.13.1~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://rallly.co/fr"
demo = "https://app.rallly.co/polls"
admindoc = "https://support.rallly.co/introduction"
code = "https://github.com/lukevella/rallly"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "2500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/orhtej2/rallly-build/releases/download/v4.13.1/rallly-web-release-amd64.tar.gz"
    amd64.sha256 = "7865c49e7a40db00e879bfffb64e8a76bd175bec1e97f159cb455b21ae4c976d"

    arm64.url = "https://github.com/orhtej2/rallly-build/releases/download/v4.13.1/rallly-web-release-arm64.tar.gz"
    arm64.sha256 = "4a64054304bbb60dffb8c449c5be7711e0553777f5530cc6ba57b937fe660986"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/orhtej2/rallly-build"
    autoupdate.asset.amd64 = "rallly-web-release-amd64\\.tar\\.gz"
    autoupdate.asset.arm64 = "rallly-web-release-arm64.tar.gz"
    

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    admin.url = "/control-panel"
    admin.allowed = "admins"
    api.show_tile = false
    api.protected = true

    [resources.ports]
    main.default = 3000

    [resources.apt]
    packages = "postgresql"
    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"
