packaging_format = 2

id = "rallly"
name = "Rallly"
description.en = "Tool for creating scheduling polls"
description.fr = "Outil de création de sondages de planification"

version = "4.15.2~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://rallly.co/fr"
demo = "https://app.rallly.co/polls"
admindoc = "https://support.rallly.co/introduction"
code = "https://github.com/lukevella/rallly"

[integration]
yunohost = ">= 12.1.40"
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "2500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/orhtej2/rallly-build/releases/download/v4.15.2/rallly-web-release-amd64.tar.gz"
    amd64.sha256 = "0ed34a519ce2f2a990b2b55fc21d0fa3cfd62d9d301c935514b1f8f8bb495c16"

    arm64.url = "https://github.com/orhtej2/rallly-build/releases/download/v4.15.2/rallly-web-release-arm64.tar.gz"
    arm64.sha256 = "285bddb40e42f6249c7c1a6a585c78d7d1657e7e8b441cf33df8f68f29e1592b"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/orhtej2/rallly-build"
    autoupdate.asset.amd64 = "rallly-web-release-amd64\\.tar\\.gz"
    autoupdate.asset.arm64 = "rallly-web-release-arm64.tar.gz"
    
    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    admin.url = "/control-panel"
    admin.allowed = "admins"
    api.show_tile = false
    api.protected = true

    [resources.ports]
    main.default = 3000

    [resources.apt]
    packages = "postgresql"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"
