#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set_default --key=admin_mail --value=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Group-meeting manager" --log="/var/log/$app/$app.log"

#=================================================
# BUILD THE APP
#=================================================
ynh_script_progression "Building the app..."

pushd $install_dir/
	set -o allexport
    source "$install_dir/.env"
    set +o allexport
    ynh_hide_warnings corepack enable
    ynh_hide_warnings npm install -g corepack@latest
    ynh_hide_warnings ynh_exec_as_app corepack prepare pnpm@9 --activate
	ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" pnpm add -w turbo
	ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" pnpm add -w prisma
	ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" pnpm turbo prune --scope=@rallly/web

	ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" pnpm install --frozen-lockfile --aggregate-output
	ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" pnpm db:generate 
	ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 NODE_OPTIONS="--max-old-space-size=3000" pnpm build
	ynh_hide_warnings ynh_exec_as_app CYPRESS_INSTALL_BINARY=0 DIRECT_DATABASE_URL="postgres://$db_user:$db_pwd@127.0.0.1:5432/$db_name" NODE_OPTIONS="--max-old-space-size=3000" pnpm db:deploy

    #remove unneeded files
    ynh_hide_warnings ynh_exec_as_app CI=true pnpm prune --prod --ignore-scripts
    ynh_hide_warnings ynh_exec_as_app CI=true pnpm store prune
popd

#Remove unneeded files
ynh_safe_rm "$install_dir"/.local
ynh_safe_rm "$install_dir"/node_modules
ynh_safe_rm "$install_dir"/apps/web/.next/cache
ynh_safe_rm "$install_dir"/.cache
ynh_safe_rm "$install_dir"/.turbo
ynh_safe_rm "$install_dir"/.vscode
ynh_safe_rm "$install_dir"/.github

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
